version: '3'

services:
  web:
    build: ./statisticsService
    command: python3 app.py
    volumes:
    - ./statisticsService:/code
    ports:
    - "5000:5000"
    environment:
    - DATABASE_NAME=pnp_portal
    - DATABASE_USER=pnp_portal
    - DATABASE_PASSWORD=%y0nQq68
    - DATABASE_PORT=3306
    - DATABASE_HOST=37.97.227.232
    - SECRET_KEY=x&=v)*(38ab&q9y-+)ic*k-=y=!=u%!19tquq3b(cjf^w&fkdg
    - DEBUG_MODE=True
